### ISSUE TITLE
Thin provisioning

### ISSUE THREAD

**Issue by Foxite** [ccremer/kubernetes-zfs-provisioner#101]
Currently space is reserved when the dataset is created. What do you think about making this optional, essentially making the PVs thinly-provisioned? This should probably be an option in the storage class.

**Comment by Foxite** [comment]
I don't have much experience with go but I've looked over the code and I'm pretty sure I can implement and test this. I'll open a PR (hopefully) today.

**Comment by ccremer** [comment]
Nice idea for probably a niche usage.

In quick online searches I couldn't find any hints about the capacity parameter in PVC, indicating whether it's OK to under-provision storage. As a user, when I request a PVC of 50GiB I would be very surprised and confused in cases where storage runs out earlier than 50Gib because underlying storage-box is overprovisioned with thinly-provisioned-volumes.

I'm not against this feature, since this provisioner is probably niche itself, being not-so-scalable anyway ;)
But thin-provisioning has its drawback and I think we should make users properly aware :)
